### ISSUE TITLE
popularity function

### ISSUE THREAD

**Issue by zapponejosh** [calebkirkish/uw-project1#11]
Estimate trail popularity from number of reviews, avg rating, maybe distance from large cities?
This will take in the trails array of trail objects and add a popularity rating to each trail object

**Comment by angelinama** [comment]
- [ ] Get current time hour
- [ ] Using address to get popular hours. Example: https://documentation.besttime.app/?shell#new-forecast
- [ ] Besttime API now have analysis[day_int].hour_analysis.intensity_nr int Hour intensity_nr indicates how busy the venue is on a scale of 5, ranging from -2 to 2 . 1st Iteration, we could use 0 as the threshold, if intensity_nr for current hour >0, we filter the place our
- [ ] Fallback logic
