### ISSUE TITLE
Create design styles/standards

### ISSUE THREAD

**Issue by zapponejosh** [calebkirkish/uw-project1#19]
- [x] color scheme
- [x] fonts
- [x] semanticUI features we will use
- [x] standard styles for basic elements (h1, h2, h3, etc.)

**Comment by JonPhoenix** [comment]
Design standards progress:

![Screen Shot 2020-07-23 at 6 18 26 PM](https://user-images.githubusercontent.com/65391199/88353642-2ceca380-cd13-11ea-99f8-3a0ff9a7745d.png)

![Screen Shot 2020-07-23 at 6 33 44 PM](https://user-images.githubusercontent.com/65391199/88353648-30802a80-cd13-11ea-8678-caecc8a5f84c.png)

https://semantic-ui.com/introduction/new.html#/twoFour

![design-stardards-options_1](https://user-images.githubusercontent.com/65391199/88353693-54dc0700-cd13-11ea-9563-9d9a46ee596b.png)

![design-stardards-options_2](https://user-images.githubusercontent.com/65391199/88353698-59a0bb00-cd13-11ea-9d56-b47617cff36a.png)

![design-stardards-options_3](https://user-images.githubusercontent.com/65391199/88353700-5b6a7e80-cd13-11ea-99f2-5e8befeb76af.png)

**Comment by JonPhoenix** [comment]
https://semantic-ui.com/introduction/new.html#/twoFour

**Comment by JonPhoenix** [comment]
![design-stardards-options_1](https://user-images.githubusercontent.com/65391199/88353961-46dab600-cd14-11ea-8e3f-e473c70f0ad3.png)

**Comment by JonPhoenix** [comment]
https://unsplash.com/s/photos/hiking-trail
