### ISSUE TITLE
Wire-framing/frontend mockup 

### ISSUE THREAD

**Issue by zapponejosh** [calebkirkish/uw-project1#5]
Prepare to start creating our design!
- [x] quick sketch or a digital wireframe that gives an idea of the layout and UX
- [x] determine how we will display elements in both desktop and mobile
- [x] Begin design on any elements you want to use 

- [ ] Finalize brand identity and feel for the site off of our initial conversation

**Comment by JonPhoenix** [comment]
![portview1-1](https://user-images.githubusercontent.com/65391199/88123030-e8c89a00-cb7e-11ea-8dfa-68ae0ad298c1.jpg)
![portview1-2](https://user-images.githubusercontent.com/65391199/88123068-fda52d80-cb7e-11ea-970f-1eb402207612.jpg)
![portview1-3](https://user-images.githubusercontent.com/65391199/88123075-00a01e00-cb7f-11ea-980f-5fee3bad444c.jpg)
![portview2-1](https://user-images.githubusercontent.com/65391199/88123079-0269e180-cb7f-11ea-8667-042e555ced71.jpg)

**Comment by JonPhoenix** [comment]
Sketches round 1

**Comment by zapponejosh** [comment]
Wanted to document what we talked about needing to be added to the start screen. 

- Current Location button so the user can click and the browser will use geolocation to get their location instead of entering a city or zipcode 
- Radius from location

The other filters we talked about adding might be something we add to the top of the tile view later on.

**Comment by JonPhoenix** [comment]
Also:

- Responsive design for mobile viewports is a priority over desktop
