### ISSUE TITLE
Breakdown of tasks

### ISSUE THREAD

**Issue by zapponejosh** [calebkirkish/uw-project1#6]
Break down the project into reasonable steps that can be divided into tasks for team members and feature branches

@zapponejosh can turn these into issues for our board

**Comment by angelinama** [comment]
Task 1: open/close filter + Covid-risk filter

- [ ] - parse in the list of trails
- [ ] - loop through the list, get the address to use Google geocoding to get county, state information for CovidAPI usage, also get place_Id to use in Google API for place information, include open/close, open hour
- [ ] - Implement a filter to either separate open places vs. closed ones or only show open places
- [ ] - Fallback logic for places without open/close information and/or without covid data

Task 2:  popular hour filter
- [ ] Get current time hour
- [ ] Using address to get popular hours. Example: https://documentation.besttime.app/?shell#new-forecast
- [ ] Besttime API now have analysis[day_int].hour_analysis.intensity_nr int Hour intensity_nr indicates how busy the venue is on a scale of 5, ranging from -2 to 2 . 1st Iteration, we could use 0 as the threshold, if intensity_nr for current hour >0, we filter the place our
- [ ] Fallback logic

**Comment by angelinama** [comment]
Breakdown the core features for our minimum viable product. Close this issue for now
