### ISSUE TITLE
Get Trail Data

### ISSUE THREAD

**Issue by zapponejosh** [calebkirkish/uw-project1#8]
Feature 1. Finding a list of trails based on a radius from hardcoded Seattle using max distance and lat/lon.
Create an array of objects from the JSON data. filtering out closed trails.
To add in each object:

- status
- location
- @DanGillette25  add to this list

**Comment by angelinama** [comment]
Reorganize issues to features

**Comment by DanGillette25** [comment]
This should be good to go

**Comment by zapponejosh** [comment]
@DanGillette25 I created this new column for QA. Once your function and everything is done create a PR for Angelina to work with and she can give you her notes. that way we don't close something out until it has been actually merged to master
